# Docs for the Azure Web Apps Deploy action

name: Build and deploy WAR app to Azure Web App - renodissdos

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Create ROOT.war file
        run: |
          mkdir target
          jar cvf target\ROOT.war *
        shell: cmd

      - name: Verify WAR file
        run: |
          dir target
        shell: cmd

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: 'target\ROOT.war'

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6BC291C6CB5446349BA372018BAC79DB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B76C63C1971246FDB28C2F3841978463 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_738BB5A88CC440E0B0CF44EB52AC0EFE }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'renodissdos'
          slot-name: 'Production'
          package: 'ROOT.war'
